[deps]
BattMo = "6f0c0536-3c2c-4762-a987-c605a8a6f898"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Jutul = "2b460a1a-8a2b-45b2-b125-b5c536396eb9"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
